// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoIndividual_2da_Tarea_.Modelos;

namespace ProyectoIndividual_2da_Tarea_.Migrations
{
    [DbContext(typeof(AutoloteDataContext))]
    partial class AutoloteDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProyectoIndividual_2da_Tarea_.Modelos.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color");

                    b.Property<int>("DetalleCarroid");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Modelo");

                    b.HasKey("Id");

                    b.HasIndex("DetalleCarroid");

                    b.ToTable("Carros","dbo");
                });

            modelBuilder.Entity("ProyectoIndividual_2da_Tarea_.Modelos.DetalleCarro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cilindraje");

                    b.Property<int>("Fecha");

                    b.Property<string>("Motor");

                    b.HasKey("Id");

                    b.ToTable("DetalleCarros");
                });

            modelBuilder.Entity("ProyectoIndividual_2da_Tarea_.Modelos.Carro", b =>
                {
                    b.HasOne("ProyectoIndividual_2da_Tarea_.Modelos.DetalleCarro", "DetalleCarro")
                        .WithMany("Carros")
                        .HasForeignKey("DetalleCarroid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
